# makefile for lmfit
#
#
include $(MAKECFG).$(SYSTEM)



INCLUDE= -I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/analysis -I/data/fit/aj/cmpfit-1.2/
SRC = lmfit_test.c lmfit_test.h
OBJS = lmfit_test.o
INC=$(IPATH)/superdarn
DSTPATH=$(LIBPATH)
OUTPUT=lmfit_test
LINK="1"



include $(MAKELIB).$(SYSTEM)
