# Makefile for radar library
# ========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
SRC=mergedata.c
OBJS = mergedata.o
INC=$(IPATH)/superdarn
DSTPATH=$(LIBPATH)
OUTPUT = merge
LINK="1"



include $(MAKELIB).$(SYSTEM)
