# Makefile for dmap library
# =========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general
SRC=dmap.c
OBJS = dmap.o
INC=$(IPATH)/general
DSTPATH=$(LIBPATH)
OUTPUT = dmap
LINK="1"

















include $(MAKELIB).$(SYSTEM)
